# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JDyAh1MWawTenNipCr9duurnJClUAQgE
"""

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread ("photo_2024-10-22_23-02-03.jpg")
cv2_imshow(rasm)

qora= cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(qora)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread ("2005.jpg")
cv2_imshow(rasm)

qora= cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(qora)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread ("0207.jpg")
cv2_imshow(rasm)

qora= cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(qora)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread ("2024.jpg")
cv2_imshow(rasm)

qora= cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(qora)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread ("2023.jpg")
cv2_imshow(rasm)

qora= cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(qora)